### ISSUE TITLE
Plugin does not properly function in remote development

### ISSUE THREAD

**Issue by pfyod** [nizienko/property_switcher#9]
Generally, extension seem to be activated, and recognizes the ".propswitch" file, shows values in the status bar. 

However:

1. Clicking on the status bar widget does not open property selection. It only shows the popup with current values when you hover over it;
2. There's no option to set a shortcut (I think only "Client" plugins can do it though, but see below).

When you install the plugin as a "Client" plugin, IDE fails to start. Here's the log:
```
IDE cannot start with the following stack trace:
2024-02-08 09:26:57,190 [     30]   INFO - #c.i.p.i.b.AppStarter - ------------------------------------------------------ IDE STARTED ------------------------------------------------------
2024-02-08 09:26:57,244 [     84]   INFO - #c.i.u.i.PageCacheUtils - File page caching params:
2024-02-08 09:26:57,245 [     85]   INFO - #c.i.u.i.PageCacheUtils - 	DEFAULT_PAGE_SIZE: 10485760
2024-02-08 09:26:57,246 [     86]   INFO - #c.i.u.i.PageCacheUtils - 	Direct memory to use, max: 4116709376
2024-02-08 09:26:57,246 [     86]   INFO - #c.i.u.i.PageCacheUtils - 	FilePageCache: regular + lock-free (LOCK_FREE_PAGE_CACHE_ENABLED:true)
2024-02-08 09:26:57,248 [     88]   INFO - #c.i.u.i.PageCacheUtils - 	NEW_PAGE_CACHE_MEMORY_FRACTION: 0.20000000298023224
2024-02-08 09:26:57,279 [    119]   INFO - #c.i.u.i.PageCacheUtils - 	Regular FilePageCache: 503316478 bytes
2024-02-08 09:26:57,280 [    120]   INFO - #c.i.u.i.PageCacheUtils - 	New     FilePageCache: 125829122 bytes (+ up to 10.0% overflow)
2024-02-08 09:26:57,280 [    120]   INFO - #c.i.u.i.PageCacheUtils - 	DirectByteBuffers pool: 104857600 bytes
2024-02-08 09:26:57,286 [    126]   INFO - #c.i.p.b.ModuleBasedProductLoadingStrategy - New classpath roots:
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\product-client.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\modules.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\app-client.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\annotations.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\util-8.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\rd.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\bouncy-castle.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\lib-client.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\util_rt.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\util.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\forms_rt.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\jps-model.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\stats.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\external-system-rt.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\error-prone-annotations.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\groovy.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\byte-buddy-agent.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\grpc.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\protobuf.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\product.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\jsch-agent.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\externalProcess-rt.jar
C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib\async-profiler.jar
2024-02-08 09:26:57,345 [    185]   INFO - #c.i.p.i.b.AppStarter - JNA library (64-bit) loaded in 142 ms
2024-02-08 09:26:57,382 [    222]   INFO - #c.i.p.i.b.AppStarter - IDE: IntelliJ IDEA (build #JBC-233.14015.106, Thu, 25 Jan 2024 05:01:00 GMT)
2024-02-08 09:26:57,383 [    223]   INFO - #c.i.p.i.b.AppStarter - OS: Windows (10.0)
2024-02-08 09:26:57,383 [    223]   INFO - #c.i.p.i.b.AppStarter - JRE: 17.0.9+7-b1087.11, amd64 (JetBrains s.r.o.)
2024-02-08 09:26:57,384 [    224]   INFO - #c.i.p.i.b.AppStarter - JVM: 17.0.9+7-b1087.11 (OpenJDK 64-Bit Server VM)
2024-02-08 09:26:57,389 [    229]   INFO - #c.i.p.i.b.AppStarter - PID: 9692
2024-02-08 09:26:57,391 [    231]   INFO - #c.i.p.i.b.AppStarter - JVM options: [exit, -XX:ErrorFile=C:\Users\REDACTED\\java_error_in_jetbrains_client64_%p.log, -XX:HeapDumpPath=C:\Users\REDACTED\\java_error_in_jetbrains_client64.hprof, -Xms128m, -Xmx1500m, -XX:ReservedCodeCacheSize=512m, -XX:+UseG1GC, -XX:SoftRefLRUPolicyMSPerMB=50, -XX:CICompilerCount=2, -XX:+HeapDumpOnOutOfMemoryError, -XX:-OmitStackTraceInFastThrow, -XX:+IgnoreUnrecognizedVMOptions, -XX:CompileCommand=exclude,com/intellij/openapi/vfs/impl/FilePartNodeRoot,trieDescend, -ea, -Dsun.io.useCanonCaches=false, -Dsun.java2d.metal=true, -Djbr.catch.SIGABRT=true, -Djdk.http.auth.tunneling.disabledSchemes="", -Djdk.attach.allowAttachSelf=true, -Djdk.module.illegalAccess.silent=true, -Dkotlinx.coroutines.debug=off, -Xmx3945m, -Djb.vmOptionsFile=C:\Users\REDACTED\AppData\Roaming\\JetBrains\\JetBrainsClient233.14015.106\jetbrains_client64.exe.vmoptions, -Djava.system.class.loader=com.intellij.util.lang.PathClassLoader, -Didea.vendor.name=JetBrains, -Didea.paths.selector=JetBrainsClient233.14015.106, -Djna.boot.library.path=C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d/lib/jna/amd64, -Dpty4j.preferred.native.folder=C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d/lib/pty4j, -Djna.nosys=true, -Djna.noclasspath=true, -Dintellij.platform.runtime.repository.path=C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d/modules/module-descriptors.jar, -Dintellij.platform.root.module=intellij.cwm.guest, -Dintellij.platform.product.mode=frontend, -Didea.platform.prefix=JetBrainsClient, -Dide.no.platform.update=true, -Didea.initially.ask.config=never, -Didea.paths.customizer=com.intellij.platform.ide.impl.startup.multiProcess.PerProcessPathCustomizer, -Dsplash=true, -Daether.connector.resumeDownloads=false, --add-opens=java.base/java.io=ALL-UNNAMED, --add-opens=java.base/java.lang=ALL-UNNAMED, --add-opens=java.base/java.lang.ref=ALL-UNNAMED, --add-opens=java.base/java.lang.reflect=ALL-UNNAMED, --add-opens=java.base/java.net=ALL-UNNAMED, --add-opens=java.base/java.nio=ALL-UNNAMED, --add-opens=java.base/java.nio.charset=ALL-UNNAMED, --add-opens=java.base/java.text=ALL-UNNAMED, --add-opens=java.base/java.time=ALL-UNNAMED, --add-opens=java.base/java.util=ALL-UNNAMED, --add-opens=java.base/java.util.concurrent=ALL-UNNAMED, --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED, --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED, --add-opens=java.base/jdk.internal.vm=ALL-UNNAMED, --add-opens=java.base/sun.nio.ch=ALL-UNNAMED, --add-opens=java.base/sun.nio.fs=ALL-UNNAMED, --add-opens=java.base/sun.security.ssl=ALL-UNNAMED, --add-opens=java.base/sun.security.util=ALL-UNNAMED, --add-opens=java.base/sun.net.dns=ALL-UNNAMED, --add-opens=java.desktop/java.awt=ALL-UNNAMED, --add-opens=java.desktop/java.awt.dnd.peer=ALL-UNNAMED, --add-opens=java.desktop/java.awt.event=ALL-UNNAMED, --add-opens=java.desktop/java.awt.image=ALL-UNNAMED, --add-opens=java.desktop/java.awt.peer=ALL-UNNAMED, --add-opens=java.desktop/java.awt.font=ALL-UNNAMED, --add-opens=java.desktop/javax.swing=ALL-UNNAMED, --add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED, --add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED, --add-opens=java.desktop/sun.awt.datatransfer=ALL-UNNAMED, --add-opens=java.desktop/sun.awt.image=ALL-UNNAMED, --add-opens=java.desktop/sun.awt.windows=ALL-UNNAMED, --add-opens=java.desktop/sun.awt=ALL-UNNAMED, --add-opens=java.desktop/sun.font=ALL-UNNAMED, --add-opens=java.desktop/sun.java2d=ALL-UNNAMED, --add-opens=java.desktop/sun.swing=ALL-UNNAMED, --add-opens=java.desktop/com.sun.java.swing=ALL-UNNAMED, --add-opens=jdk.attach/sun.tools.attach=ALL-UNNAMED, --add-opens=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED, --add-opens=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED, --add-opens=jdk.jdi/com.sun.tools.jdi=ALL-UNNAMED, -Dide.native.launcher=true, -Djcef.sandbox.ptr=000001E4F165C040]
2024-02-08 09:26:57,392 [    232]   INFO - #c.i.p.i.b.AppStarter - args: thinClient gwws://127.0.0.1:63342/gateway/clientLink?uid=2fa273a1-9936-43cd-9368-35705e22841e#jt=a71993b7-a4f5-4704-a174-964df2febe93&p=IU&fp=704F4AA052BD2725B293A5553A51C239E7EF138CFCDE24A85CCE6525479ABCC6&cb=233.14015.106&jb=17.0.9b1087.11&gtw_build=233.14015.129&newUi=true
2024-02-08 09:26:57,393 [    233]   INFO - #c.i.p.i.b.AppStarter - library path: C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Eclipse Adoptium\jdk-17.0.1.12-hotspot\bin;C:\Program Files\Eclipse Adoptium\jdk-11.0.13.8-hotspot\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\Program Files\PuTTY\;C:\Users\REDACTED\AppData\Local\Microsoft\WindowsApps;C:\Users\REDACTED\.deno\bin;C:\Users\REDACTED\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\REDACTED\AppData\Local\JetBrains\Toolbox\scripts;C:\projects\bin\apache-maven-3.9.2\bin;C:\gstreamer\1.0\mingw_x86_64\bin;.
2024-02-08 09:26:57,393 [    233]   INFO - #c.i.p.i.b.AppStarter - boot library path: C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\jbr\bin
2024-02-08 09:26:57,417 [    257]   INFO - #c.i.p.i.b.AppStarter - locale=en_US JNU=Cp1252 file.encoding=Cp1252
    idea.config.path=C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClient233.14015.106\tmp\per_process_config_0
    idea.system.path=C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClient233.14015.106\tmp\per_process_system_0
    idea.plugins.path=C:\Users\REDACTED\AppData\Roaming\JetBrains\JetBrainsClient233.14015.106\plugins
    idea.log.path=C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClient233.14015.106\log\2024-02-08_at_09-26-56
2024-02-08 09:26:57,425 [    265]   INFO - #c.i.p.i.b.AppStarter - CPU cores: 12; ForkJoinPool.commonPool: java.util.concurrent.ForkJoinPool@5734859f[Running, parallelism = 11, size = 0, active = 0, running = 0, steals = 0, tasks = 0, submissions = 0]; factory: com.intellij.concurrency.IdeaForkJoinWorkerThreadFactory@1d6e9085
2024-02-08 09:26:57,462 [    302]   INFO - #c.i.i.p.PluginManager - Using broken plugins file from IDE distribution
2024-02-08 09:26:57,595 [    435]   INFO - #c.i.i.p.PluginManager - Module intellij.markdown.model is not enabled because dependency com.intellij.modules.xml is not available
Module intellij.markdown.xml is not enabled because dependency com.intellij.modules.xml is not available
Module intellij.markdown.images is not enabled because dependency com.intellij.platform.images is not available
Module intellij.markdown.frontmatter.toml is not enabled because dependency org.intellij.intelliLang is not available
Module intellij.markdown.frontmatter.yaml is not enabled because dependency org.intellij.intelliLang is not available
Module intellij.markdown.frontmatter is not enabled because dependency org.intellij.intelliLang is not available
Module intellij.markdown.fenceInjection is not enabled because dependency org.intellij.intelliLang is not available
Module intellij.terminal.sh is not enabled because dependency com.jetbrains.sh is not available
Module intellij.terminal/cloud is not enabled because dependency com.intellij.modules.remoteServers is not available
2024-02-08 09:26:57,621 [    461]   INFO - #c.i.i.p.PluginManager - Loaded bundled plugins: Terminal for JetBrains Client (233.14015.106), Java Extension for Remote Client (233.14015.106), Async Profiler for IDE Performance Testing (233.14015.106), Markdown (233.14015.106), IDEA CORE (233.14015.106), Terminal (233.14015.106), Markdown for JetBrains Client (233.14015.106), Performance Testing (233.14015.106)
2024-02-08 09:26:57,621 [    461]   INFO - #c.i.i.p.PluginManager - Loaded custom plugins: Nginx Configuration (2022.1.1), GraphQL (233.13135.65), Property Switcher (0.9.4), PlantUML Integration (7.5.1-IJ2023.2), Rainbow Brackets (2024.2.0)
2024-02-08 09:26:59,588 [   2428]   INFO - STDOUT - Debug | RdCoroutineScope          | 15:DefaultDispatcher-worker-3 | RdCoroutineHost has been overridden 
2024-02-08 09:26:59,605 [   2445]   INFO - #c.j.t.s.s.ThinClientSharedConfigFolderApplicationInitializedListener - Process per connection mode is enabled, configuration files with be synchronized with C:\Users\REDACTED\AppData\Roaming\JetBrains\JetBrainsClient233.14015.106.
2024-02-08 09:26:59,613 [   2453]   INFO - #c.i.o.v.n.p.FSRecords - VFS health-check enabled: first after 600000 ms, and each following 43200000 ms
2024-02-08 09:26:59,752 [   2592]   INFO - #c.i.a.o.PathMacrosImpl - Loaded path macros: {MAVEN_REPOSITORY=C:\Users\REDACTED\.m2\repository}
2024-02-08 09:26:59,763 [   2603]   INFO - #c.i.o.u.r.RegistryManager - Registry values changed by user: THIN_CLIENT_EXTERNAL_SYSTEM.system.in.process = true, debugger.new.tool.window.layout = true, ide.experimental.ui = true, ide.experimental.ui.inter.font = false, idea.plugins.compatible.build = , rdclient.asyncActions = true, rdclient.backend.actionHandlers = false
2024-02-08 09:26:59,769 [   2609]   INFO - #c.i.o.u.r.RegistryValue - Registry value 'rdclient.backend.actionHandlers' has changed to 'false'
2024-02-08 09:26:59,913 [   2753]   INFO - #c.i.i.p.ExpiredPluginsState - Plugins to skip: []
2024-02-08 09:26:59,924 [   2764]   INFO - #c.i.o.v.n.p.PersistentFSLoader - VFS uses 'fast' names enumerator (over mmapped file)
2024-02-08 09:26:59,926 [   2766]   INFO - #c.i.o.v.n.p.PersistentFSLoader - VFS uses content storage over new FilePageCache
2024-02-08 09:26:59,926 [   2766]   INFO - #c.i.o.v.n.p.PersistentFSLoader - VFS uses streamlined attributes storage (over mmapped file)
2024-02-08 09:26:59,931 [   2771]   INFO - #c.i.o.v.n.p.PersistentFSLoader - VFS uses content hash storage over mmapped file
2024-02-08 09:27:00,023 [   2863] SEVERE - #c.i.o.f.i.FileTypeManagerImpl - Trying to add extensions to non-registered file type JSON [Plugin: com.intellij.lang.jsgraphql]
com.intellij.diagnostic.PluginException: Trying to add extensions to non-registered file type JSON [Plugin: com.intellij.lang.jsgraphql]
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.loadFileTypeBeans(FileTypeManagerImpl.java:420)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initStandardFileTypes(FileTypeManagerImpl.java:295)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initializeComponent(FileTypeManagerImpl.java:587)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:143)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:931)
	at com.intellij.serviceContainer.ServiceInstanceInitializer.createInstance$suspendImpl(ServiceInstanceInitializer.kt:41)
	at com.intellij.serviceContainer.ServiceInstanceInitializer.createInstance(ServiceInstanceInitializer.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invokeSuspend(LazyInstanceHolder.kt:162)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invokeSuspend(LazyInstanceHolder.kt:160)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.initialize(LazyInstanceHolder.kt:145)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.access$initialize(LazyInstanceHolder.kt:13)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.tryInitialize(LazyInstanceHolder.kt:135)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt:95)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance$suspendImpl(LazyInstanceHolder.kt:83)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.instance(InstanceContainerImpl.kt:67)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsync(ComponentManagerImpl.kt:993)
	at com.intellij.platform.ide.bootstrap.AppServicePreloadingKt$postAppRegistered$1$fileTypeManagerJob$1.invokeSuspend(appServicePreloading.kt:211)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-02-08 09:27:00,067 [   2907] SEVERE - #c.i.o.f.i.FileTypeManagerImpl - IntelliJ IDEA 2023.3.3  Build #JBC-233.14015.106
2024-02-08 09:27:00,068 [   2908] SEVERE - #c.i.o.f.i.FileTypeManagerImpl - JDK: 17.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-02-08 09:27:00,069 [   2909] SEVERE - #c.i.o.f.i.FileTypeManagerImpl - OS: Windows 10
2024-02-08 09:27:00,073 [   2913] SEVERE - #c.i.o.f.i.FileTypeManagerImpl - Plugin to blame: GraphQL version: 233.13135.65
2024-02-08 09:27:00,074 [   2914] SEVERE - #c.i.o.f.i.FileTypeManagerImpl - Last Action: 
2024-02-08 09:27:00,317 [   3157]   WARN - #c.i.o.e.c.i.EditorColorsManagerImpl - Cannot find scheme: Monokai from plugins: com.intellij.lang.jsgraphql
2024-02-08 09:27:00,327 [   3167]   INFO - #c.i.o.a.i.ActionManagerImpl - keymap "Eclipse" not found PluginDescriptor(name=IDEA CORE, id=com.intellij, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib, version=233.14015.106, package=com.intellij.platform.feedback, isBundled=true)
2024-02-08 09:27:00,328 [   3168]   INFO - #c.i.o.a.i.ActionManagerImpl - keymap "NetBeans 6.5" not found PluginDescriptor(name=IDEA CORE, id=com.intellij, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib, version=233.14015.106, package=com.intellij.platform.feedback, isBundled=true)
2024-02-08 09:27:00,329 [   3169]   INFO - #c.i.o.a.i.ActionManagerImpl - keymap "Visual Studio" not found PluginDescriptor(name=IDEA CORE, id=com.intellij, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\lib, version=233.14015.106, package=com.intellij.platform.feedback, isBundled=true)
2024-02-08 09:27:00,351 [   3191]   INFO - #c.i.o.a.i.ActionManagerImpl - keymap "VSCode" not found PluginDescriptor(name=Terminal, id=org.jetbrains.plugins.terminal, descriptorPath=plugin.xml, path=~\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\plugins\terminal, version=233.14015.106, package=org.jetbrains.plugins.terminal, isBundled=true)
2024-02-08 09:27:00,389 [   3229]   INFO - #o.j.i.BuiltInServerManager - built-in server started, port 63343
2024-02-08 09:27:00,459 [   3299]   INFO - #c.j.r.a.ActionsOverrider - Action manager created. Traversing IDE backends: []
2024-02-08 09:27:00,538 [   3378]   INFO - #c.i.u.n.s.CertificateManager - Default SSL context initialized
2024-02-08 09:27:01,284 [   4124]   INFO - #c.i.o.v.n.p.PersistentFSLoader - VFS: impl (expected) version=846656, 0 file records, 0 content blobs
2024-02-08 09:27:01,294 [   4134]   INFO - #c.i.o.v.n.p.FSRecordsImpl - VFS scanned: file-by-name index was populated
2024-02-08 09:27:01,296 [   4136]   INFO - #c.i.o.v.n.p.FSRecordsImpl - VFS initialized: 1408 ms, 0 failed attempts, 0 error(s) were recovered
2024-02-08 09:27:01,312 [   4152]   INFO - STDOUT - Debug | RdCoroutineScope          | 1:main          | RdCoroutineHost has been reset 
2024-02-08 09:27:01,321 [   4161]   INFO - #c.i.u.s.SvgCacheManager - SVG icon cache is closed
2024-02-08 09:27:01,328 [   4168]   INFO - STDERR - 
2024-02-08 09:27:01,329 [   4169]   INFO - STDERR - Start Failed
2024-02-08 09:27:01,330 [   4170]   INFO - STDERR - Internal error. Please refer to https://jb.gg/ide/critical-startup-errors
2024-02-08 09:27:01,330 [   4170]   INFO - STDERR - 
2024-02-08 09:27:01,330 [   4170]   INFO - STDERR - java.lang.NoClassDefFoundError: com/intellij/json/JsonLanguage
2024-02-08 09:27:01,330 [   4170]   INFO - STDERR - 	at com.github.nizienko.propertiesSwitcher.fileType.PropertiesTemplateFileType.<init>(PropertiesTemplateFileType.kt:13)
2024-02-08 09:27:01,331 [   4171]   INFO - STDERR - 	at com.github.nizienko.propertiesSwitcher.fileType.PropertiesTemplateFileType.<clinit>(PropertiesTemplateFileType.kt:17)
2024-02-08 09:27:01,331 [   4171]   INFO - STDERR - 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
2024-02-08 09:27:01,331 [   4171]   INFO - STDERR - 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
2024-02-08 09:27:01,331 [   4171]   INFO - STDERR - 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42)
2024-02-08 09:27:01,331 [   4171]   INFO - STDERR - 	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:185)
2024-02-08 09:27:01,332 [   4172]   INFO - STDERR - 	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1132)
2024-02-08 09:27:01,332 [   4172]   INFO - STDERR - 	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1113)
2024-02-08 09:27:01,332 [   4172]   INFO - STDERR - 	at java.base/java.lang.reflect.Field.get(Field.java:425)
2024-02-08 09:27:01,332 [   4172]   INFO - STDERR - 	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiateFileTypeBean(FileTypeManagerImpl.java:497)
2024-02-08 09:27:01,332 [   4172]   INFO - STDERR - 	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.mergeOrInstantiateFileTypeBean(FileTypeManagerImpl.java:466)
2024-02-08 09:27:01,333 [   4173]   INFO - STDERR - 	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiatePendingFileTypes(FileTypeManagerImpl.java:459)
2024-02-08 09:27:01,333 [   4173]   INFO - STDERR - 	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initializeComponent(FileTypeManagerImpl.java:590)
2024-02-08 09:27:01,333 [   4173]   INFO - STDERR - 	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:143)
2024-02-08 09:27:01,333 [   4173]   INFO - STDERR - 	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
2024-02-08 09:27:01,334 [   4174]   INFO - STDERR - 	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:931)
2024-02-08 09:27:01,334 [   4174]   INFO - STDERR - 	at com.intellij.serviceContainer.ServiceInstanceInitializer.createInstance$suspendImpl(ServiceInstanceInitializer.kt:41)
2024-02-08 09:27:01,334 [   4174]   INFO - STDERR - 	at com.intellij.serviceContainer.ServiceInstanceInitializer.createInstance(ServiceInstanceInitializer.kt)
2024-02-08 09:27:01,334 [   4174]   INFO - STDERR - 	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invokeSuspend(LazyInstanceHolder.kt:162)
2024-02-08 09:27:01,335 [   4175]   INFO - STDERR - 	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
2024-02-08 09:27:01,335 [   4175]   INFO - STDERR - 	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
2024-02-08 09:27:01,335 [   4175]   INFO - STDERR - 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
2024-02-08 09:27:01,335 [   4175]   INFO - STDERR - 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
2024-02-08 09:27:01,336 [   4176]   INFO - STDERR - 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
2024-02-08 09:27:01,336 [   4176]   INFO - STDERR - 	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invokeSuspend(LazyInstanceHolder.kt:160)
2024-02-08 09:27:01,336 [   4176]   INFO - STDERR - 	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
2024-02-08 09:27:01,337 [   4177]   INFO - STDERR - 	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
2024-02-08 09:27:01,337 [   4177]   INFO - STDERR - 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
2024-02-08 09:27:01,337 [   4177]   INFO - STDERR - 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
2024-02-08 09:27:01,337 [   4177]   INFO - STDERR - 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
2024-02-08 09:27:01,338 [   4178]   INFO - STDERR - 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
2024-02-08 09:27:01,338 [   4178]   INFO - STDERR - 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
2024-02-08 09:27:01,338 [   4178]   INFO - STDERR - 	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.initialize(LazyInstanceHolder.kt:145)
2024-02-08 09:27:01,338 [   4178]   INFO - STDERR - 	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.access$initialize(LazyInstanceHolder.kt:13)
2024-02-08 09:27:01,338 [   4178]   INFO - STDERR - 	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.tryInitialize(LazyInstanceHolder.kt:135)
2024-02-08 09:27:01,339 [   4179]   INFO - STDERR - 	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt:95)
2024-02-08 09:27:01,339 [   4179]   INFO - STDERR - 	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance$suspendImpl(LazyInstanceHolder.kt:83)
2024-02-08 09:27:01,339 [   4179]   INFO - STDERR - 	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt)
2024-02-08 09:27:01,340 [   4180]   INFO - STDERR - 	at com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.instance(InstanceContainerImpl.kt:67)
2024-02-08 09:27:01,340 [   4180]   INFO - STDERR - 	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsync(ComponentManagerImpl.kt:993)
2024-02-08 09:27:01,340 [   4180]   INFO - STDERR - 	at com.intellij.platform.ide.bootstrap.AppServicePreloadingKt$postAppRegistered$1$fileTypeManagerJob$1.invokeSuspend(appServicePreloading.kt:211)
2024-02-08 09:27:01,340 [   4180]   INFO - STDERR - 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-02-08 09:27:01,341 [   4181]   INFO - STDERR - 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
2024-02-08 09:27:01,341 [   4181]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
2024-02-08 09:27:01,341 [   4181]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
2024-02-08 09:27:01,341 [   4181]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
2024-02-08 09:27:01,342 [   4182]   INFO - STDERR - 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-02-08 09:27:01,342 [   4182]   INFO - STDERR - Caused by: java.lang.ClassNotFoundException: com.intellij.json.JsonLanguage PluginClassLoader(plugin=PluginDescriptor(name=Property Switcher, id=com.github.nizienko.properties_switcher, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\JetBrainsClient233.14015.106\plugins\Property Switcher, version=0.9.4, package=null, isBundled=false), packagePrefix=null, state=active)
2024-02-08 09:27:01,342 [   4182]   INFO - STDERR - 	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:156)
2024-02-08 09:27:01,342 [   4182]   INFO - STDERR - 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
2024-02-08 09:27:01,343 [   4183]   INFO - STDERR - 	... 47 more
2024-02-08 09:27:01,343 [   4183]   INFO - STDERR - 
2024-02-08 09:27:01,343 [   4183]   INFO - STDERR - -----
2024-02-08 09:27:01,343 [   4183]   INFO - STDERR - Your JRE: 17.0.9+7-b1087.11 amd64 (JetBrains s.r.o.)
2024-02-08 09:27:01,344 [   4184]   INFO - STDERR - C:\Users\REDACTED\AppData\Local\JetBrains\JetBrainsClientDist\JetBrainsClient-233.14015.106.jbr.win.zip-245a51d581.ide.d\jbr
2024-02-08 09:27:12,185 [  15025] SEVERE - #c.i.o.u.ShutDownTracker - com/intellij/json/JsonLanguage
java.lang.NoClassDefFoundError: com/intellij/json/JsonLanguage
	at com.github.nizienko.propertiesSwitcher.fileType.PropertiesTemplateFileType.<init>(PropertiesTemplateFileType.kt:13)
	at com.github.nizienko.propertiesSwitcher.fileType.PropertiesTemplateFileType.<clinit>(PropertiesTemplateFileType.kt:17)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:185)
	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1132)
	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1113)
	at java.base/java.lang.reflect.Field.get(Field.java:425)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiateFileTypeBean(FileTypeManagerImpl.java:497)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.mergeOrInstantiateFileTypeBean(FileTypeManagerImpl.java:466)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiatePendingFileTypes(FileTypeManagerImpl.java:459)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initializeComponent(FileTypeManagerImpl.java:590)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:143)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:48)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:931)
	at com.intellij.serviceContainer.ServiceInstanceInitializer.createInstance$suspendImpl(ServiceInstanceInitializer.kt:41)
	at com.intellij.serviceContainer.ServiceInstanceInitializer.createInstance(ServiceInstanceInitializer.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invokeSuspend(LazyInstanceHolder.kt:162)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invokeSuspend(LazyInstanceHolder.kt:160)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.initialize(LazyInstanceHolder.kt:145)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.access$initialize(LazyInstanceHolder.kt:13)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.tryInitialize(LazyInstanceHolder.kt:135)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt:95)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance$suspendImpl(LazyInstanceHolder.kt:83)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.instance(InstanceContainerImpl.kt:67)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsync(ComponentManagerImpl.kt:993)
	at com.intellij.platform.ide.bootstrap.AppServicePreloadingKt$postAppRegistered$1$fileTypeManagerJob$1.invokeSuspend(appServicePreloading.kt:211)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.ClassNotFoundException: com.intellij.json.JsonLanguage PluginClassLoader(plugin=PluginDescriptor(name=Property Switcher, id=com.github.nizienko.properties_switcher, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\JetBrainsClient233.14015.106\plugins\Property Switcher, version=0.9.4, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:156)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 47 more
2024-02-08 09:27:12,188 [  15028] SEVERE - #c.i.o.u.ShutDownTracker - IntelliJ IDEA 2023.3.3  Build #JBC-233.14015.106
2024-02-08 09:27:12,189 [  15029] SEVERE - #c.i.o.u.ShutDownTracker - JDK: 17.0.9; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-02-08 09:27:12,189 [  15029] SEVERE - #c.i.o.u.ShutDownTracker - OS: Windows 10
2024-02-08 09:27:12,189 [  15029] SEVERE - #c.i.o.u.ShutDownTracker - Plugin to blame: Property Switcher version: 0.9.4
2024-02-08 09:27:12,190 [  15030] SEVERE - #c.i.o.u.ShutDownTracker - Last Action: 
2024-02-08 09:27:12,207 [  15047]   INFO - #c.i.p.i.b.AppStarter - ------------------------------------------------------ IDE SHUTDOWN ------------------------------------------------------
```

**Comment by kool79** [comment]
@pfyod 
the last error java.lang.NoClassDefFoundError: com/intellij/json/JsonLanguage should be fixed by #13. Can you try it?

**Comment by pfyod** [comment]
@kool79 JsonLanguage error is gone, but plugin still does not work - just shows the title/popup on hover, does nothing when clicked on.
